package com.bs.dao.mapping;

import com.bs.dao.entity.Treat;
import com.bs.dao.entity.TreatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int countByExample(TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int deleteByExample(TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int insert(Treat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int insertSelective(Treat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    List<Treat> selectByExample(TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    Treat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Treat record, @Param("example") TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Treat record, @Param("example") TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Treat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Treat record);
}