package com.bs.dao.entity;

import java.io.Serializable;

public class OrderBooking implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.ORDER_ID
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.VISIT_TIME
     *
     * @mbggenerated
     */
    private String visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.AGE
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.MAIN_CONDITIONS
     *
     * @mbggenerated
     */
    private String mainConditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_booking.FILEIDS
     *
     * @mbggenerated
     */
    private String fileids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_booking
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.ID
     *
     * @return the value of order_booking.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.ID
     *
     * @param id the value for order_booking.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.ORDER_ID
     *
     * @return the value of order_booking.ORDER_ID
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.ORDER_ID
     *
     * @param orderId the value for order_booking.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.VISIT_TIME
     *
     * @return the value of order_booking.VISIT_TIME
     *
     * @mbggenerated
     */
    public String getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.VISIT_TIME
     *
     * @param visitTime the value for order_booking.VISIT_TIME
     *
     * @mbggenerated
     */
    public void setVisitTime(String visitTime) {
        this.visitTime = visitTime == null ? null : visitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.NAME
     *
     * @return the value of order_booking.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.NAME
     *
     * @param name the value for order_booking.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.TELEPHONE
     *
     * @return the value of order_booking.TELEPHONE
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.TELEPHONE
     *
     * @param telephone the value for order_booking.TELEPHONE
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.AGE
     *
     * @return the value of order_booking.AGE
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.AGE
     *
     * @param age the value for order_booking.AGE
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.SEX
     *
     * @return the value of order_booking.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.SEX
     *
     * @param sex the value for order_booking.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.ADDRESS
     *
     * @return the value of order_booking.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.ADDRESS
     *
     * @param address the value for order_booking.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.MAIN_CONDITIONS
     *
     * @return the value of order_booking.MAIN_CONDITIONS
     *
     * @mbggenerated
     */
    public String getMainConditions() {
        return mainConditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.MAIN_CONDITIONS
     *
     * @param mainConditions the value for order_booking.MAIN_CONDITIONS
     *
     * @mbggenerated
     */
    public void setMainConditions(String mainConditions) {
        this.mainConditions = mainConditions == null ? null : mainConditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_booking.FILEIDS
     *
     * @return the value of order_booking.FILEIDS
     *
     * @mbggenerated
     */
    public String getFileids() {
        return fileids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_booking.FILEIDS
     *
     * @param fileids the value for order_booking.FILEIDS
     *
     * @mbggenerated
     */
    public void setFileids(String fileids) {
        this.fileids = fileids == null ? null : fileids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_booking
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderBooking other = (OrderBooking) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getVisitTime() == null ? other.getVisitTime() == null : this.getVisitTime().equals(other.getVisitTime()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getMainConditions() == null ? other.getMainConditions() == null : this.getMainConditions().equals(other.getMainConditions()))
            && (this.getFileids() == null ? other.getFileids() == null : this.getFileids().equals(other.getFileids()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_booking
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getVisitTime() == null) ? 0 : getVisitTime().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getMainConditions() == null) ? 0 : getMainConditions().hashCode());
        result = prime * result + ((getFileids() == null) ? 0 : getFileids().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_booking
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", visitTime=").append(visitTime);
        sb.append(", name=").append(name);
        sb.append(", telephone=").append(telephone);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", address=").append(address);
        sb.append(", mainConditions=").append(mainConditions);
        sb.append(", fileids=").append(fileids);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}