package com.bs.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Treat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.AGE
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.ID_CODE
     *
     * @mbggenerated
     */
    private String idCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.FACE
     *
     * @mbggenerated
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.BACK
     *
     * @mbggenerated
     */
    private String back;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.LEVEL
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.WORK_YEARS
     *
     * @mbggenerated
     */
    private String workYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.SERVICE_EXP
     *
     * @mbggenerated
     */
    private String serviceExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.FILEIDS
     *
     * @mbggenerated
     */
    private String fileids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column treat.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table treat
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.ID
     *
     * @return the value of treat.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.ID
     *
     * @param id the value for treat.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.ACCOUNT_ID
     *
     * @return the value of treat.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.ACCOUNT_ID
     *
     * @param accountId the value for treat.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.NAME
     *
     * @return the value of treat.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.NAME
     *
     * @param name the value for treat.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.SEX
     *
     * @return the value of treat.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.SEX
     *
     * @param sex the value for treat.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.AGE
     *
     * @return the value of treat.AGE
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.AGE
     *
     * @param age the value for treat.AGE
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.ADDRESS
     *
     * @return the value of treat.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.ADDRESS
     *
     * @param address the value for treat.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.ID_CODE
     *
     * @return the value of treat.ID_CODE
     *
     * @mbggenerated
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.ID_CODE
     *
     * @param idCode the value for treat.ID_CODE
     *
     * @mbggenerated
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.FACE
     *
     * @return the value of treat.FACE
     *
     * @mbggenerated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.FACE
     *
     * @param face the value for treat.FACE
     *
     * @mbggenerated
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.BACK
     *
     * @return the value of treat.BACK
     *
     * @mbggenerated
     */
    public String getBack() {
        return back;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.BACK
     *
     * @param back the value for treat.BACK
     *
     * @mbggenerated
     */
    public void setBack(String back) {
        this.back = back == null ? null : back.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.LEVEL
     *
     * @return the value of treat.LEVEL
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.LEVEL
     *
     * @param level the value for treat.LEVEL
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.WORK_YEARS
     *
     * @return the value of treat.WORK_YEARS
     *
     * @mbggenerated
     */
    public String getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.WORK_YEARS
     *
     * @param workYears the value for treat.WORK_YEARS
     *
     * @mbggenerated
     */
    public void setWorkYears(String workYears) {
        this.workYears = workYears == null ? null : workYears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.SERVICE_EXP
     *
     * @return the value of treat.SERVICE_EXP
     *
     * @mbggenerated
     */
    public String getServiceExp() {
        return serviceExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.SERVICE_EXP
     *
     * @param serviceExp the value for treat.SERVICE_EXP
     *
     * @mbggenerated
     */
    public void setServiceExp(String serviceExp) {
        this.serviceExp = serviceExp == null ? null : serviceExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.FILEIDS
     *
     * @return the value of treat.FILEIDS
     *
     * @mbggenerated
     */
    public String getFileids() {
        return fileids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.FILEIDS
     *
     * @param fileids the value for treat.FILEIDS
     *
     * @mbggenerated
     */
    public void setFileids(String fileids) {
        this.fileids = fileids == null ? null : fileids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.STATUS
     *
     * @return the value of treat.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.STATUS
     *
     * @param status the value for treat.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.CREATE_TIME
     *
     * @return the value of treat.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.CREATE_TIME
     *
     * @param createTime the value for treat.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column treat.UPDATE_TIME
     *
     * @return the value of treat.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column treat.UPDATE_TIME
     *
     * @param updateTime the value for treat.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Treat other = (Treat) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getIdCode() == null ? other.getIdCode() == null : this.getIdCode().equals(other.getIdCode()))
            && (this.getFace() == null ? other.getFace() == null : this.getFace().equals(other.getFace()))
            && (this.getBack() == null ? other.getBack() == null : this.getBack().equals(other.getBack()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getWorkYears() == null ? other.getWorkYears() == null : this.getWorkYears().equals(other.getWorkYears()))
            && (this.getServiceExp() == null ? other.getServiceExp() == null : this.getServiceExp().equals(other.getServiceExp()))
            && (this.getFileids() == null ? other.getFileids() == null : this.getFileids().equals(other.getFileids()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getIdCode() == null) ? 0 : getIdCode().hashCode());
        result = prime * result + ((getFace() == null) ? 0 : getFace().hashCode());
        result = prime * result + ((getBack() == null) ? 0 : getBack().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getWorkYears() == null) ? 0 : getWorkYears().hashCode());
        result = prime * result + ((getServiceExp() == null) ? 0 : getServiceExp().hashCode());
        result = prime * result + ((getFileids() == null) ? 0 : getFileids().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", address=").append(address);
        sb.append(", idCode=").append(idCode);
        sb.append(", face=").append(face);
        sb.append(", back=").append(back);
        sb.append(", level=").append(level);
        sb.append(", workYears=").append(workYears);
        sb.append(", serviceExp=").append(serviceExp);
        sb.append(", fileids=").append(fileids);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}