package com.bs.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class FileStorageInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.FILE_ID
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.FILE_KEY
     *
     * @mbggenerated
     */
    private String fileKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.FILE_BUCKET
     *
     * @mbggenerated
     */
    private String fileBucket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.FILE_DOMAIN
     *
     * @mbggenerated
     */
    private String fileDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.FILE_SIZE
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.FILE_MIME_TYPE
     *
     * @mbggenerated
     */
    private String fileMimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_storage_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.FILE_ID
     *
     * @return the value of file_storage_info.FILE_ID
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.FILE_ID
     *
     * @param fileId the value for file_storage_info.FILE_ID
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.FILE_KEY
     *
     * @return the value of file_storage_info.FILE_KEY
     *
     * @mbggenerated
     */
    public String getFileKey() {
        return fileKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.FILE_KEY
     *
     * @param fileKey the value for file_storage_info.FILE_KEY
     *
     * @mbggenerated
     */
    public void setFileKey(String fileKey) {
        this.fileKey = fileKey == null ? null : fileKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.FILE_BUCKET
     *
     * @return the value of file_storage_info.FILE_BUCKET
     *
     * @mbggenerated
     */
    public String getFileBucket() {
        return fileBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.FILE_BUCKET
     *
     * @param fileBucket the value for file_storage_info.FILE_BUCKET
     *
     * @mbggenerated
     */
    public void setFileBucket(String fileBucket) {
        this.fileBucket = fileBucket == null ? null : fileBucket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.FILE_DOMAIN
     *
     * @return the value of file_storage_info.FILE_DOMAIN
     *
     * @mbggenerated
     */
    public String getFileDomain() {
        return fileDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.FILE_DOMAIN
     *
     * @param fileDomain the value for file_storage_info.FILE_DOMAIN
     *
     * @mbggenerated
     */
    public void setFileDomain(String fileDomain) {
        this.fileDomain = fileDomain == null ? null : fileDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.FILE_SIZE
     *
     * @return the value of file_storage_info.FILE_SIZE
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.FILE_SIZE
     *
     * @param fileSize the value for file_storage_info.FILE_SIZE
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.FILE_MIME_TYPE
     *
     * @return the value of file_storage_info.FILE_MIME_TYPE
     *
     * @mbggenerated
     */
    public String getFileMimeType() {
        return fileMimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.FILE_MIME_TYPE
     *
     * @param fileMimeType the value for file_storage_info.FILE_MIME_TYPE
     *
     * @mbggenerated
     */
    public void setFileMimeType(String fileMimeType) {
        this.fileMimeType = fileMimeType == null ? null : fileMimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.CREATE_TIME
     *
     * @return the value of file_storage_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.CREATE_TIME
     *
     * @param createTime the value for file_storage_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_storage_info.ACCOUNT_ID
     *
     * @return the value of file_storage_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_storage_info.ACCOUNT_ID
     *
     * @param accountId the value for file_storage_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FileStorageInfo other = (FileStorageInfo) that;
        return (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getFileKey() == null ? other.getFileKey() == null : this.getFileKey().equals(other.getFileKey()))
            && (this.getFileBucket() == null ? other.getFileBucket() == null : this.getFileBucket().equals(other.getFileBucket()))
            && (this.getFileDomain() == null ? other.getFileDomain() == null : this.getFileDomain().equals(other.getFileDomain()))
            && (this.getFileSize() == null ? other.getFileSize() == null : this.getFileSize().equals(other.getFileSize()))
            && (this.getFileMimeType() == null ? other.getFileMimeType() == null : this.getFileMimeType().equals(other.getFileMimeType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getFileKey() == null) ? 0 : getFileKey().hashCode());
        result = prime * result + ((getFileBucket() == null) ? 0 : getFileBucket().hashCode());
        result = prime * result + ((getFileDomain() == null) ? 0 : getFileDomain().hashCode());
        result = prime * result + ((getFileSize() == null) ? 0 : getFileSize().hashCode());
        result = prime * result + ((getFileMimeType() == null) ? 0 : getFileMimeType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileKey=").append(fileKey);
        sb.append(", fileBucket=").append(fileBucket);
        sb.append(", fileDomain=").append(fileDomain);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", fileMimeType=").append(fileMimeType);
        sb.append(", createTime=").append(createTime);
        sb.append(", accountId=").append(accountId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}