package com.bs.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileStorageInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected int limitClauseCount = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public FileStorageInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileIdIsNull() {
            addCriterion("FILE_ID is null");
            return (Criteria) this;
        }

        public Criteria andFileIdIsNotNull() {
            addCriterion("FILE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFileIdEqualTo(String value) {
            addCriterion("FILE_ID =", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotEqualTo(String value) {
            addCriterion("FILE_ID <>", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThan(String value) {
            addCriterion("FILE_ID >", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_ID >=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThan(String value) {
            addCriterion("FILE_ID <", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThanOrEqualTo(String value) {
            addCriterion("FILE_ID <=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLike(String value) {
            addCriterion("FILE_ID like", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotLike(String value) {
            addCriterion("FILE_ID not like", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdIn(List<String> values) {
            addCriterion("FILE_ID in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotIn(List<String> values) {
            addCriterion("FILE_ID not in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdBetween(String value1, String value2) {
            addCriterion("FILE_ID between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotBetween(String value1, String value2) {
            addCriterion("FILE_ID not between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileKeyIsNull() {
            addCriterion("FILE_KEY is null");
            return (Criteria) this;
        }

        public Criteria andFileKeyIsNotNull() {
            addCriterion("FILE_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andFileKeyEqualTo(String value) {
            addCriterion("FILE_KEY =", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyNotEqualTo(String value) {
            addCriterion("FILE_KEY <>", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyGreaterThan(String value) {
            addCriterion("FILE_KEY >", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_KEY >=", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyLessThan(String value) {
            addCriterion("FILE_KEY <", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyLessThanOrEqualTo(String value) {
            addCriterion("FILE_KEY <=", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyLike(String value) {
            addCriterion("FILE_KEY like", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyNotLike(String value) {
            addCriterion("FILE_KEY not like", value, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyIn(List<String> values) {
            addCriterion("FILE_KEY in", values, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyNotIn(List<String> values) {
            addCriterion("FILE_KEY not in", values, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyBetween(String value1, String value2) {
            addCriterion("FILE_KEY between", value1, value2, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileKeyNotBetween(String value1, String value2) {
            addCriterion("FILE_KEY not between", value1, value2, "fileKey");
            return (Criteria) this;
        }

        public Criteria andFileBucketIsNull() {
            addCriterion("FILE_BUCKET is null");
            return (Criteria) this;
        }

        public Criteria andFileBucketIsNotNull() {
            addCriterion("FILE_BUCKET is not null");
            return (Criteria) this;
        }

        public Criteria andFileBucketEqualTo(String value) {
            addCriterion("FILE_BUCKET =", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketNotEqualTo(String value) {
            addCriterion("FILE_BUCKET <>", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketGreaterThan(String value) {
            addCriterion("FILE_BUCKET >", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_BUCKET >=", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketLessThan(String value) {
            addCriterion("FILE_BUCKET <", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketLessThanOrEqualTo(String value) {
            addCriterion("FILE_BUCKET <=", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketLike(String value) {
            addCriterion("FILE_BUCKET like", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketNotLike(String value) {
            addCriterion("FILE_BUCKET not like", value, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketIn(List<String> values) {
            addCriterion("FILE_BUCKET in", values, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketNotIn(List<String> values) {
            addCriterion("FILE_BUCKET not in", values, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketBetween(String value1, String value2) {
            addCriterion("FILE_BUCKET between", value1, value2, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileBucketNotBetween(String value1, String value2) {
            addCriterion("FILE_BUCKET not between", value1, value2, "fileBucket");
            return (Criteria) this;
        }

        public Criteria andFileDomainIsNull() {
            addCriterion("FILE_DOMAIN is null");
            return (Criteria) this;
        }

        public Criteria andFileDomainIsNotNull() {
            addCriterion("FILE_DOMAIN is not null");
            return (Criteria) this;
        }

        public Criteria andFileDomainEqualTo(String value) {
            addCriterion("FILE_DOMAIN =", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotEqualTo(String value) {
            addCriterion("FILE_DOMAIN <>", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainGreaterThan(String value) {
            addCriterion("FILE_DOMAIN >", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_DOMAIN >=", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainLessThan(String value) {
            addCriterion("FILE_DOMAIN <", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainLessThanOrEqualTo(String value) {
            addCriterion("FILE_DOMAIN <=", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainLike(String value) {
            addCriterion("FILE_DOMAIN like", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotLike(String value) {
            addCriterion("FILE_DOMAIN not like", value, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainIn(List<String> values) {
            addCriterion("FILE_DOMAIN in", values, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotIn(List<String> values) {
            addCriterion("FILE_DOMAIN not in", values, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainBetween(String value1, String value2) {
            addCriterion("FILE_DOMAIN between", value1, value2, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileDomainNotBetween(String value1, String value2) {
            addCriterion("FILE_DOMAIN not between", value1, value2, "fileDomain");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNull() {
            addCriterion("FILE_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNotNull() {
            addCriterion("FILE_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andFileSizeEqualTo(Long value) {
            addCriterion("FILE_SIZE =", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotEqualTo(Long value) {
            addCriterion("FILE_SIZE <>", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThan(Long value) {
            addCriterion("FILE_SIZE >", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("FILE_SIZE >=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThan(Long value) {
            addCriterion("FILE_SIZE <", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThanOrEqualTo(Long value) {
            addCriterion("FILE_SIZE <=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeIn(List<Long> values) {
            addCriterion("FILE_SIZE in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotIn(List<Long> values) {
            addCriterion("FILE_SIZE not in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeBetween(Long value1, Long value2) {
            addCriterion("FILE_SIZE between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotBetween(Long value1, Long value2) {
            addCriterion("FILE_SIZE not between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeIsNull() {
            addCriterion("FILE_MIME_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeIsNotNull() {
            addCriterion("FILE_MIME_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeEqualTo(String value) {
            addCriterion("FILE_MIME_TYPE =", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeNotEqualTo(String value) {
            addCriterion("FILE_MIME_TYPE <>", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeGreaterThan(String value) {
            addCriterion("FILE_MIME_TYPE >", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_MIME_TYPE >=", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeLessThan(String value) {
            addCriterion("FILE_MIME_TYPE <", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeLessThanOrEqualTo(String value) {
            addCriterion("FILE_MIME_TYPE <=", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeLike(String value) {
            addCriterion("FILE_MIME_TYPE like", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeNotLike(String value) {
            addCriterion("FILE_MIME_TYPE not like", value, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeIn(List<String> values) {
            addCriterion("FILE_MIME_TYPE in", values, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeNotIn(List<String> values) {
            addCriterion("FILE_MIME_TYPE not in", values, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeBetween(String value1, String value2) {
            addCriterion("FILE_MIME_TYPE between", value1, value2, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andFileMimeTypeNotBetween(String value1, String value2) {
            addCriterion("FILE_MIME_TYPE not between", value1, value2, "fileMimeType");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("ACCOUNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("ACCOUNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("ACCOUNT_ID >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("ACCOUNT_ID <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("ACCOUNT_ID in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("ACCOUNT_ID not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("ACCOUNT_ID between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACCOUNT_ID not between", value1, value2, "accountId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_storage_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_storage_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}