package com.bs.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ORDER_CODE
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.TREAT_ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer treatAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.AUDIT_DESC
     *
     * @mbggenerated
     */
    private String auditDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.REFUSE_REASON
     *
     * @mbggenerated
     */
    private String refuseReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ID
     *
     * @return the value of order_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ID
     *
     * @param id the value for order_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ORDER_CODE
     *
     * @return the value of order_info.ORDER_CODE
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ORDER_CODE
     *
     * @param orderCode the value for order_info.ORDER_CODE
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ACCOUNT_ID
     *
     * @return the value of order_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ACCOUNT_ID
     *
     * @param accountId the value for order_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.TREAT_ACCOUNT_ID
     *
     * @return the value of order_info.TREAT_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getTreatAccountId() {
        return treatAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.TREAT_ACCOUNT_ID
     *
     * @param treatAccountId the value for order_info.TREAT_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setTreatAccountId(Integer treatAccountId) {
        this.treatAccountId = treatAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.TYPE_ID
     *
     * @return the value of order_info.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.TYPE_ID
     *
     * @param typeId the value for order_info.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ORDER_STATUS
     *
     * @return the value of order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ORDER_STATUS
     *
     * @param orderStatus the value for order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.AUDIT_DESC
     *
     * @return the value of order_info.AUDIT_DESC
     *
     * @mbggenerated
     */
    public String getAuditDesc() {
        return auditDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.AUDIT_DESC
     *
     * @param auditDesc the value for order_info.AUDIT_DESC
     *
     * @mbggenerated
     */
    public void setAuditDesc(String auditDesc) {
        this.auditDesc = auditDesc == null ? null : auditDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.REFUSE_REASON
     *
     * @return the value of order_info.REFUSE_REASON
     *
     * @mbggenerated
     */
    public String getRefuseReason() {
        return refuseReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.REFUSE_REASON
     *
     * @param refuseReason the value for order_info.REFUSE_REASON
     *
     * @mbggenerated
     */
    public void setRefuseReason(String refuseReason) {
        this.refuseReason = refuseReason == null ? null : refuseReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.CREATE_TIME
     *
     * @return the value of order_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.CREATE_TIME
     *
     * @param createTime the value for order_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.UPDATE_TIME
     *
     * @return the value of order_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.UPDATE_TIME
     *
     * @param updateTime the value for order_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderInfo other = (OrderInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderCode() == null ? other.getOrderCode() == null : this.getOrderCode().equals(other.getOrderCode()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getTreatAccountId() == null ? other.getTreatAccountId() == null : this.getTreatAccountId().equals(other.getTreatAccountId()))
            && (this.getTypeId() == null ? other.getTypeId() == null : this.getTypeId().equals(other.getTypeId()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getAuditDesc() == null ? other.getAuditDesc() == null : this.getAuditDesc().equals(other.getAuditDesc()))
            && (this.getRefuseReason() == null ? other.getRefuseReason() == null : this.getRefuseReason().equals(other.getRefuseReason()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderCode() == null) ? 0 : getOrderCode().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getTreatAccountId() == null) ? 0 : getTreatAccountId().hashCode());
        result = prime * result + ((getTypeId() == null) ? 0 : getTypeId().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getAuditDesc() == null) ? 0 : getAuditDesc().hashCode());
        result = prime * result + ((getRefuseReason() == null) ? 0 : getRefuseReason().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderCode=").append(orderCode);
        sb.append(", accountId=").append(accountId);
        sb.append(", treatAccountId=").append(treatAccountId);
        sb.append(", typeId=").append(typeId);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", auditDesc=").append(auditDesc);
        sb.append(", refuseReason=").append(refuseReason);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}