package com.bs.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Suggestion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.FEEDBACK_DESC
     *
     * @mbggenerated
     */
    private String feedbackDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.SCORE
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.FILEIDS
     *
     * @mbggenerated
     */
    private String fileids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suggestion.AUDIT_DESC
     *
     * @mbggenerated
     */
    private String auditDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggestion
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.ID
     *
     * @return the value of suggestion.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.ID
     *
     * @param id the value for suggestion.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.ACCOUNT_ID
     *
     * @return the value of suggestion.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.ACCOUNT_ID
     *
     * @param accountId the value for suggestion.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.NAME
     *
     * @return the value of suggestion.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.NAME
     *
     * @param name the value for suggestion.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.TELEPHONE
     *
     * @return the value of suggestion.TELEPHONE
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.TELEPHONE
     *
     * @param telephone the value for suggestion.TELEPHONE
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.FEEDBACK_DESC
     *
     * @return the value of suggestion.FEEDBACK_DESC
     *
     * @mbggenerated
     */
    public String getFeedbackDesc() {
        return feedbackDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.FEEDBACK_DESC
     *
     * @param feedbackDesc the value for suggestion.FEEDBACK_DESC
     *
     * @mbggenerated
     */
    public void setFeedbackDesc(String feedbackDesc) {
        this.feedbackDesc = feedbackDesc == null ? null : feedbackDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.SCORE
     *
     * @return the value of suggestion.SCORE
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.SCORE
     *
     * @param score the value for suggestion.SCORE
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.FILEIDS
     *
     * @return the value of suggestion.FILEIDS
     *
     * @mbggenerated
     */
    public String getFileids() {
        return fileids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.FILEIDS
     *
     * @param fileids the value for suggestion.FILEIDS
     *
     * @mbggenerated
     */
    public void setFileids(String fileids) {
        this.fileids = fileids == null ? null : fileids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.STATUS
     *
     * @return the value of suggestion.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.STATUS
     *
     * @param status the value for suggestion.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.CREATE_TIME
     *
     * @return the value of suggestion.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.CREATE_TIME
     *
     * @param createTime the value for suggestion.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.UPDATE_TIME
     *
     * @return the value of suggestion.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.UPDATE_TIME
     *
     * @param updateTime the value for suggestion.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suggestion.AUDIT_DESC
     *
     * @return the value of suggestion.AUDIT_DESC
     *
     * @mbggenerated
     */
    public String getAuditDesc() {
        return auditDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suggestion.AUDIT_DESC
     *
     * @param auditDesc the value for suggestion.AUDIT_DESC
     *
     * @mbggenerated
     */
    public void setAuditDesc(String auditDesc) {
        this.auditDesc = auditDesc == null ? null : auditDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Suggestion other = (Suggestion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getFeedbackDesc() == null ? other.getFeedbackDesc() == null : this.getFeedbackDesc().equals(other.getFeedbackDesc()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getFileids() == null ? other.getFileids() == null : this.getFileids().equals(other.getFileids()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAuditDesc() == null ? other.getAuditDesc() == null : this.getAuditDesc().equals(other.getAuditDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getFeedbackDesc() == null) ? 0 : getFeedbackDesc().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getFileids() == null) ? 0 : getFileids().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAuditDesc() == null) ? 0 : getAuditDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggestion
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", name=").append(name);
        sb.append(", telephone=").append(telephone);
        sb.append(", feedbackDesc=").append(feedbackDesc);
        sb.append(", score=").append(score);
        sb.append(", fileids=").append(fileids);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", auditDesc=").append(auditDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}